const { Router } = require('express');
const { registerPatient, registerHealthProvider, verifyOtpReset, resetPassword, login, removeProfileImage, updateProfileImage, updateIDFront, updateIDBack, updateHPCNAQualification, updateFinalQualification, updatePatientDetails, updateHealthProvider, changePassword, deactivateAccount, getAllAppUsers, approveHealthProviderDocuments, rejectHealthProviderDocuments, updateDispensingCertificateLicence, updatePushToken, userDetails, getAppToken } = require('../../controllers/app/authController');
const { uploadSingle } = require('../../middlewares/uploadProfileImage');
const { uploadMultipleDocuments } = require('../../middlewares/uploadHealthProviderImages');
const uploadIdFront = require('../../middlewares/uploadIdFront');
const uploadannualQualification = require('../../middlewares/uploadannualQualification');
const uploadprimaryQualification = require('../../middlewares/uploadprimaryQualification');
const { uploadSingleBack } = require('../../middlewares/uploadIdBack');
const { uploadMultiple } = require('../../middlewares/uploadIDDocument');
const uploadPrescribingCertificate = require('../../middlewares/uploadPrescribingCertificate');
const { appTokenMiddleware, checkAppUser, tokenAuthMiddleware, checkUser } = require('../../middlewares/authMiddleware');
const authRouter = Router();

authRouter.post("/register-patient",appTokenMiddleware, checkAppUser, uploadMultiple, registerPatient);
authRouter.post("/register-health-provider",appTokenMiddleware, checkAppUser, uploadMultipleDocuments, registerHealthProvider);
authRouter.post("/forgot-password-verify-otp",appTokenMiddleware, checkAppUser, verifyOtpReset);
authRouter.post("/forgot-password-reset/:id",appTokenMiddleware, checkAppUser, resetPassword);
authRouter.post("/login", appTokenMiddleware, checkAppUser, login);
authRouter.get("/user-details/:id",tokenAuthMiddleware,checkUser, userDetails);
authRouter.delete("/remove-profile-image/:id",tokenAuthMiddleware,checkUser, removeProfileImage);
authRouter.put("/update-patient-details/:id",tokenAuthMiddleware,checkUser, updatePatientDetails);
authRouter.patch("/change-password/:id",tokenAuthMiddleware,checkUser, changePassword);
authRouter.patch("/deactivate-account/:id",tokenAuthMiddleware,checkUser, deactivateAccount);
authRouter.put("/update-health-provider-details/:id",tokenAuthMiddleware,checkUser, updateHealthProvider);
authRouter.patch("/upload-profile-image/:id",tokenAuthMiddleware,checkUser,uploadSingle, updateProfileImage);
authRouter.patch("/update-id-front/:id",tokenAuthMiddleware,checkUser, uploadIdFront.uploadSingleFront, updateIDFront);
authRouter.patch("/update-id-back/:id",tokenAuthMiddleware,checkUser, uploadSingleBack, updateIDBack);
authRouter.patch("/update-annual-qualification/:id",tokenAuthMiddleware,checkUser, uploadannualQualification.uploadSingleAnnual, updateHPCNAQualification);
authRouter.patch("/update-primary-qualification/:id",tokenAuthMiddleware,checkUser, uploadprimaryQualification.uploadSinglePrimary, updateFinalQualification);
authRouter.patch("/update-prescribing-certificate/:id", tokenAuthMiddleware,checkUser, uploadPrescribingCertificate.uploadPrescribingCertificate, updateDispensingCertificateLicence);
authRouter.get("/all-users",tokenAuthMiddleware,checkUser, getAllAppUsers);
authRouter.patch("/approve-documents/:id",tokenAuthMiddleware,checkUser, approveHealthProviderDocuments);
authRouter.patch("/reject-documents/:id", tokenAuthMiddleware,checkUser, rejectHealthProviderDocuments);
authRouter.patch("/update-push-token/:id", tokenAuthMiddleware,checkUser, updatePushToken);
authRouter.get("/retrieve-jwt-token", getAppToken);

module.exports = authRouter;